version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pip1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rbwaca0hf8b2"
s3_prefix = "pip1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
